// <auto-generated />
namespace CrossEduAsp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddedModelsWithoutIdentityUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedModelsWithoutIdentityUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201501251433470_AddedModelsWithoutIdentityUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
